# Change these first
owner: latracal # Your GitHub organization or username, where this repository lives
repo: status.grigora.co # The name of this repository

sites:
  - name: Dashboard
    url: https://build.grigora.co
  - name: API
    url: https://api.grigora.co
  - name: Hosted Websites
    url: https://test.grigora.app
  - name: CDN
    url: https://cdn.grigora.co
  - name: Support System
    url: https://support.grigora.co
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status2.grigora.co
  # baseUrl: /your-repo-name
  logoUrl: https://www.grigora.co/fav-icon/apple-touch-icon.png
  name: Grigora System Status
  introTitle: "Check if anything is down."
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.grigora.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
